### ISSUE TITLE
[BUG] Pls help

### ISSUE THREAD

**Issue by YaZanuda111111** [Luc4sguilherme/Steam-levelup-BOT#73]
![image](https://user-images.githubusercontent.com/78689718/115956516-85004280-a4fd-11eb-9b4d-e25f23fb0f7f.png)

On one PC everything works fine, but on the other here ... How to fix it?

**Comment by YaZanuda111111** [comment]
![image](https://user-images.githubusercontent.com/78689718/115956568-c7298400-a4fd-11eb-93cf-28e6d97911ff.png)
Here is my 2 pc

**Comment by Luc4sguilherme** [comment]
Which command was used before the problem occurred? Was the trade with id: 456706 created with any command or manually?

**Comment by YaZanuda111111** [comment]
No teams. The bot was usually started and then it was usually closed. I could not find a deal with ID data.
1 The transaction is pending (this transaction has a different ID and a 15-day delay). But why then does the bot work stably on another pc?

**Comment by Luc4sguilherme** [comment]
The lib that handles steam exchanges caches the trades made by the bot. Try to clean it, go to this directory **%localappdata%\doctormckay** and delete everything.
Remove the **node_modules** folder and reinstall the dependencies again.

**Comment by YaZanuda111111** [comment]
%appdata% - npm-cache - Delete everything helped, thanks

**Comment by tbasar1** [comment]
> 

i do it but didnt fix can you help me pls
