### ISSUE TITLE
Sets4Sets

### ISSUE THREAD

**Issue by YaZanuda111111** [Luc4sguilherme/Steam-levelup-BOT#74]
where can I disable this command?
Sets4Sets

**Comment by YaZanuda111111** [comment]
I searched everything, I will be grateful if someone tells me where to find it. Thank you

**Comment by Luc4sguilherme** [comment]
You can ignore the commands in this way.

![Print](https://user-images.githubusercontent.com/29242243/116481863-6c27c200-a85a-11eb-8c90-312479942eed.PNG)
