### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Nasri69** [Luc4sguilherme/Steam-levelup-BOT#84]
Is it possible to change prices for sets? Default its `32:1 CS:GO, 12:1 HYDRA, 24:1 TF2, 1:550 Gems`

**Comment by Luc4sguilherme** [comment]
@Nasri69 Yes, you can change prices in this [file](https://github.com/Luc4sguilherme/Steam-levelup-BOT/blob/master/src/Config/rates.js).
