### ISSUE TITLE
Steam foil mode is not working.

### ISSUE THREAD

**Issue by nhk882** [Luc4sguilherme/Steam-levelup-BOT#88]
Hey,
The foil mode is not working....currently its sending 5 sets of a game just like the normal cards when I ask for !buytf 1
"Bot sent you a new trade offerHere are {SETS} cards set(s) in exchange for {TF} Key(s). View trade offer"

and do you have the buying system like 14.5 sets for 1 key ?

**Comment by Luc4sguilherme** [comment]
It is not possible to use rates with decimal numbers.

**Comment by Luc4sguilherme** [comment]
Did you set this to true in your settings?

![image](https://user-images.githubusercontent.com/29242243/152716354-0ffa453c-019a-4afc-96b5-959afb82cdfa.png)

**Comment by nhk882** [comment]
Yes, It's true.
The problem is that it sends 5 sets of a game just like the normal sets.

![Screenshot_7](https://user-images.githubusercontent.com/13215634/152723140-88a5f91f-91e1-4fe3-836b-92a88d8e44b0.jpg)

**Comment by nhk882** [comment]
> It is not possible to use rates with decimal numbers.

then how are they using it ? 
![Screenshot_8](https://user-images.githubusercontent.com/13215634/152723345-1a4f821a-7979-43d8-a72b-725bf6db06bd.jpg)

**Comment by nhk882** [comment]
> Yes, It's true. The problem is that it sends 5 sets of a game just like the normal sets.
> 
> ![Screenshot_7](https://user-images.githubusercontent.com/13215634/152723140-88a5f91f-91e1-4fe3-836b-92a88d8e44b0.jpg)

I see that you have fixed the sets name in trade comment.......but it is still sending the 5 sets of each game in foil mode.

**Comment by nhk882** [comment]
also the !check amount is counting 5 sets of a game instead of 1 in FOIL mode.

**Comment by Luc4sguilherme** [comment]
Making the changes to make it work this way would be quite difficult. So I made another script for just foil cards. Anyway I think the !CHECKONE and !BUYONE commands do what you need.

https://github.com/Luc4sguilherme/Steam-foil-levelup-BOT

**Comment by nhk882** [comment]
thank you so much for your afford.
can you send your trade offer link ?
I wanna give a little gift only if the new script works well.
