### ISSUE TITLE
download the code when i run it

### ISSUE THREAD

**Issue by zhqpower** [Luc4sguilherme/Steam-levelup-BOT#89]
An error occurred while setting cookies.
DATE: 08/02/2022 | 23:56:33 @ [ ERROR ] An error occurred while getting bot Gems inventory: Error: ETIMEDOUT
<img width="1126" alt="WeChatd4aee169cc3c9102a20cba42e0008303" src="https://user-images.githubusercontent.com/8142420/153113954-0965385c-170f-457b-bbf4-e4c8009d054d.png">

**Comment by Luc4sguilherme** [comment]
The first is an error connecting to Steam servers.
The second could have just been a consequence of the first error or it could have happened due to a very large inventory (+200k items).
