### ISSUE TITLE
Add Separated Sale Event Mode

### ISSUE THREAD

**Issue by SENPAY98K** [Luc4sguilherme/Steam-levelup-BOT#94]
Hello, 
If you have some time and the will to develop this awesome project further, i would suggest:
- Adding new mode for enabling sale events cards and sets `i.e: Summer Sale, Winter Sale` with a separated data file so we can modify it on each event ?
- Also adding a feature for trading single event cards with specific price to the mode above ?

**Comment by Luc4sguilherme** [comment]
I made a script for event cards. [See here](https://github.com/Luc4sguilherme/eventCards-BOT).

**Comment by SENPAY98K** [comment]
Wow that was super fast 👀
